
# Model
network: pilot_net_v1

conv_dropout: 0.4
dense_dropout: 0.5
l2_regularization: 0.001

# Preprocessing
crop_up: 50
crop_down: 30

# Training
epochs: 1
batch_size: 32
steer_correction: 0.2

# Dataset
dataset: data_mine